port: 40000
mode: rule
log-level: info
external-controller: 127.0.0.1:40001
proxies:
- name: Youtube不良林
  type: http
  server: buliang0.tk
  port: 6666
- name: 40010
  type: ss
  server: 207.244.67.149
  port: 39772
  cipher: aes-256-gcm
  password: CUndSZnYsPKcu6Kj8THVMBHD
- name: 40011
  type: ss
  server: 207.244.67.149
  port: 33998
  cipher: aes-256-gcm
  password: NHwQTPLCfaTMSqTnU3mjcSxe
- name: 40012
  type: vmess
  server: cm-jm.smdynet.com
  port: 20004
  cipher: auto
  uuid: a26aa399-d112-436c-8e1e-6d87b3168b3c
  alterId: 1
  network: ws
  ws-path: /
  ws-headers:
    Host: cm-jm.smdynet.com
- name: 40013
  type: vmess
  server: 138.201.150.52
  port: 33957
  cipher: auto
  uuid: 89cee221-b06c-46c5-f0d7-4fd3f4740b97
  alterId: 64
  network: tcp
  ws-path: /
  ws-headers:
    Host: ''
- name: 40014
  type: vmess
  server: vtwonet-hk-a.qjnodeip.xyz
  port: 23333
  cipher: auto
  uuid: 55D1D690-B0C1-58CA-918B-8C4783AE88BD
  alterId: 0
  network: tcp
  ws-path: /
  ws-headers:
    Host: ''
- name: 40015
  type: vmess
  server: 104.19.16.220
  port: 443
  cipher: auto
  tls: true
  uuid: aa209e52-9bfa-4c05-96b0-e962da2cb457
  alterId: 1
  network: ws
  ws-path: /xrayvws
  ws-headers:
    Host: c.1808.cf
- name: 40016
  type: vmess
  server: 104.19.79.202
  port: 443
  cipher: auto
  tls: true
  uuid: aa209e52-9bfa-4c05-96b0-e962da2cb457
  alterId: 1
  network: ws
  ws-path: /xrayvws
  ws-headers:
    Host: c.1808.cf
- name: 40017
  type: vmess
  server: 104.19.42.20
  port: 443
  cipher: auto
  tls: true
  uuid: aa209e52-9bfa-4c05-96b0-e962da2cb457
  alterId: 1
  network: ws
  ws-path: /xrayvws
  ws-headers:
    Host: c.1808.cf
- name: 40018
  type: vmess
  server: 104.27.123.78
  port: 443
  cipher: auto
  tls: true
  uuid: aa209e52-9bfa-4c05-96b0-e962da2cb457
  alterId: 1
  network: ws
  ws-path: /xrayvws
  ws-headers:
    Host: c.1808.cf
- name: 40019
  type: vmess
  server: 104.19.19.253
  port: 443
  cipher: auto
  tls: true
  uuid: aa209e52-9bfa-4c05-96b0-e962da2cb457
  alterId: 1
  network: ws
  ws-path: /xrayvws
  ws-headers:
    Host: c.1808.cf
proxy-groups:
- name: Proxy2
  type: select
  proxies:
  - Youtube不良林
- name: proxy40010
  type: select
  proxies:
  - 40010
- name: proxy40011
  type: select
  proxies:
  - 40011
- name: proxy40012
  type: select
  proxies:
  - 40012
- name: proxy40013
  type: select
  proxies:
  - 40013
- name: proxy40014
  type: select
  proxies:
  - 40014
- name: proxy40015
  type: select
  proxies:
  - 40015
- name: proxy40016
  type: select
  proxies:
  - 40016
- name: proxy40017
  type: select
  proxies:
  - 40017
- name: proxy40018
  type: select
  proxies:
  - 40018
- name: proxy40019
  type: select
  proxies:
  - 40019
rules:
- SRC-PORT,40010,proxy40010
- SRC-PORT,40011,proxy40011
- SRC-PORT,40012,proxy40012
- SRC-PORT,40013,proxy40013
- SRC-PORT,40014,proxy40014
- SRC-PORT,40015,proxy40015
- SRC-PORT,40016,proxy40016
- SRC-PORT,40017,proxy40017
- SRC-PORT,40018,proxy40018
- SRC-PORT,40019,proxy40019
